# -*- coding: utf-8 -*-
"""Florence_2_LargeOCRFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0_JMolda91YIsVU971g5tXZbG6ERM1b

# How to use Florence-2

This notebook shows how to use **Florence-2**, the foundational vision model from Microsoft, and is associated with the article **[Florence-2: How it works and how to use it](https://www.assemblyai.com/blog/florence-2-how-it-works-how-to-use)**.

**It is recommended to run this notebook in Colab - if you are coming from the [associated repository](https://github.com/AssemblyAI-Community/florence-2), you can find the link to the colab [here](https://colab.research.google.com/drive/1gD56EBmQ7MZfBkyhGtcrvHtaD2KMSm6W?usp=sharing)**.

If you run this locally you will also need to install the packages in the requirements file.

## Setup

First, we need to install packages beyond those pre-installed in Colab in order to run Florence-2.
"""

!pip install gradio pillow

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install timm flash_attn einops;

"""Next, we clone the associated repository and move the files into the working directory."""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# git clone https://github.com/AssemblyAI-Community/florence-2
# mv florence-2/** .
# rm -rf ./florence-2/

"""Now we import the packages we'll need, including the `utils.py` module from the repository that we just cloned. This file provides misellaneous functionality to make it easier to work with Florence-2."""

# Commented out IPython magic to ensure Python compatibility.
import copy

from transformers import AutoProcessor, AutoModelForCausalLM
from PIL import Image
import requests

import utils

# %matplotlib inline

"""Next we load the Florence-2 model and processor"""

model_id = 'microsoft/Florence-2-large-ft'
model = AutoModelForCausalLM.from_pretrained(model_id, trust_remote_code=True).eval().cuda()
processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)

"""And then we set these models as constants for our `utils.py` module so that the functions can utilize them as global constants."""

utils.set_model_info(model, processor)

from google.colab import drive
drive.mount('/content/drive')

"""#### Character recognition

Character recognition (OCR) tasks detect the text present in images, and optionally return bounding boxes for the identified text.

See also [vocab detection](#scrollTo=ouid-bVL53hd&line=1&uniqifier=1) to actively search for the presence of a specific word or phrase.
"""

path = "/content/drive/MyDrive/PS2-Samples-HackRX5/PS2-Samples-HackRX5/Sample1.png"
image = Image.open(path)
image_rgb = Image.open(path).convert("RGB")

task = utils.TaskType.OCR
results = utils.run_example(task, image_rgb)
print('Detected Text: ', results[task])

import gradio as gr
from PIL import Image
import utils

# OCR processing function
def extract_medical_info(image):
    # Convert image to RGB
    image_rgb = image.convert("RGB")
    # Specify the OCR task type
    task = utils.TaskType.OCR
    # Run the OCR on the image
    results = utils.run_example(task, image_rgb)
    # Extracted text (assuming results[task] contains the detected text)
    detected_text = results.get(task, "No text detected.")
    return detected_text

# Create a Gradio interface
iface = gr.Interface(
    fn=extract_medical_info,  # The function to process the image
    inputs=gr.Image(type="pil"),  # Image input for uploading medical records
    outputs="text",  # Text output to display OCR results
    title="Medical Record OCR Extractor",
    description="Upload an image of a medical record to extract the detailed text information."
)

# Launch the interface
if __name__ == "__main__":
    iface.launch()