# -*- coding: utf-8 -*-
"""HackhoundsOCR (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bsdezV7jgfqjWW86780XkprOVSxM_F71
"""

!pip install gradio

!pip install accelerate

!pip install qwen-vl-utils

!pip install optimum

!pip install auto-gptq

!pip uninstall transformers
!pip install git+https://github.com/huggingface/transformers

import gradio as gr
import torch
from transformers import Qwen2VLForConditionalGeneration, AutoProcessor
from qwen_vl_utils import process_vision_info

# Load the model and processor on available device(s)
model = Qwen2VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2-VL-7B-Instruct-GPTQ-Int4",
    torch_dtype="auto",
    device_map="auto"
)

processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct-GPTQ-Int4")

def generate_caption(image, prompt):
    messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "image": image,  # The uploaded image
                },
                {"type": "text", "text": prompt},
            ],
        }
    ]

    # Prepare the input
    text = processor.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    image_inputs, video_inputs = process_vision_info(messages)
    inputs = processor(
        text=[text],
        images=image_inputs,
        videos=video_inputs,
        padding=True,
        return_tensors="pt",
    )
    device = "cuda" if torch.cuda.is_available() else "cpu"
    inputs = inputs.to(device)

    # Generate the output
    generated_ids = model.generate(**inputs, max_new_tokens=128)
    generated_ids_trimmed = [
        out_ids[len(in_ids):] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
    ]
    output_text = processor.batch_decode(
        generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
    )
    return output_text[0]

# Define the Gradio interface
iface = gr.Interface(
    fn=generate_caption,
    inputs=[
        gr.Image(type="pil", label="Upload Image"),
        gr.Textbox(lines=2, placeholder="Enter your prompt here...", label="Prompt"),
    ],
    outputs=gr.Textbox(label="Generated Description"),
    title="Image Captioning with Qwen2-VL-7B",
    description="Upload an image and enter a prompt to get a description.",
)

if __name__ == "__main__":
    iface.launch(share=True)